version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./logs:/code/logs
      - ./error_reports:/code/error_reports

  celery_worker_1:
    build: .
    command: celery -A app.tasks worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - ./logs:/code/logs
      - ./error_reports:/code/error_reports

  celery_worker_2:
    build: .
    command: celery -A app.tasks worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - ./logs:/code/logs
      - ./error_reports:/code/error_reports

  redis:
    image: redis:7